// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5w9ouCue45p8ca8YehUsEBjwEWRCHCBw',
    appId: '1:787953937051:web:7091db05ae74f1ec2d343e',
    messagingSenderId: '787953937051',
    projectId: 'healthscout-4e38c',
    authDomain: 'healthscout-4e38c.firebaseapp.com',
    storageBucket: 'healthscout-4e38c.firebasestorage.app',
    measurementId: 'G-RQXDDM643J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsB4Wkl6XBSkqoKxdYa_cnjkeD0ilPfxA',
    appId: '1:787953937051:android:9b72b5079c688e1c2d343e',
    messagingSenderId: '787953937051',
    projectId: 'healthscout-4e38c',
    storageBucket: 'healthscout-4e38c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIo_mATnr8-WyaCooL_YwqjitKEl6ZkfY',
    appId: '1:787953937051:ios:5978e130cf05674a2d343e',
    messagingSenderId: '787953937051',
    projectId: 'healthscout-4e38c',
    storageBucket: 'healthscout-4e38c.firebasestorage.app',
    iosBundleId: 'com.example.healthscout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIo_mATnr8-WyaCooL_YwqjitKEl6ZkfY',
    appId: '1:787953937051:ios:5978e130cf05674a2d343e',
    messagingSenderId: '787953937051',
    projectId: 'healthscout-4e38c',
    storageBucket: 'healthscout-4e38c.firebasestorage.app',
    iosBundleId: 'com.example.healthscout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5w9ouCue45p8ca8YehUsEBjwEWRCHCBw',
    appId: '1:787953937051:web:0a9d5b16f01488442d343e',
    messagingSenderId: '787953937051',
    projectId: 'healthscout-4e38c',
    authDomain: 'healthscout-4e38c.firebaseapp.com',
    storageBucket: 'healthscout-4e38c.firebasestorage.app',
    measurementId: 'G-QJTLBEK3TF',
  );
}
